import { StyleSheet } from 'react-native';
export const colors = {
  bg: '#F5F3EE',
  card: '#FFFFFF',
  line: '#DFDED7',
  text: '#222923',
  muted: '#687068',
  green: '#346348',
  red: '#AF332D',
  amber: '#8C581A',
  accent: '#BC4C28',
  ink: '#263B30',
  soft: '#E9EDE6',
};
export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 22, gap: 16, paddingBottom: 40 },
  title: { fontSize: 32, fontWeight: '600', letterSpacing: -1.2, color: colors.text },
  heading: { fontSize: 19, fontWeight: '600', letterSpacing: -0.3, color: colors.text },
  text: { fontSize: 16, lineHeight: 23, color: colors.text },
  muted: { fontSize: 14, lineHeight: 21, color: colors.muted },
  label: { fontSize: 11, fontWeight: '700', letterSpacing: 1.4, color: colors.muted },
  card: {
    padding: 18,
    gap: 10,
    borderRadius: 12,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  grow: { flex: 1, gap: 4 },
  button: {
    minHeight: 50,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: colors.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: { color: '#FFFFFF', fontWeight: '600', fontSize: 15 },
  secondary: { backgroundColor: 'transparent', borderWidth: 1, borderColor: colors.line },
  secondaryText: { color: colors.text },
  input: {
    backgroundColor: colors.card,
    color: colors.text,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 8,
    padding: 15,
    minHeight: 54,
    fontSize: 16,
  },
  error: { padding: 14, borderRadius: 8, backgroundColor: '#FBEAE5', gap: 8 },
  errorText: { color: colors.red, fontSize: 15, lineHeight: 21 },
  photo: { width: 56, height: 56, borderRadius: 8, backgroundColor: colors.soft },
  count: {
    fontSize: 44,
    fontWeight: '600',
    letterSpacing: -1.5,
    color: colors.text,
    fontVariant: ['tabular-nums'],
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  badge: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: colors.soft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hero: { padding: 22, gap: 12, borderRadius: 12, backgroundColor: colors.ink },
  section: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
});
